Add virtual mode
padoa/tlsi-ins pull request #29
Opened 2023-09-27 10:05 UTC by FlorianMaPadoa

2023-09-27 13:14 UTC, Orphidios requested changes
- Prendre dans les requêtes les vrais Idam, Nom, Version ect
- Ne pas les avoirs en dure dans les mock
- Faire des class pour chaques person + Abstract class pour le typing
- Ajouter une class pour gérer le mode virtuel
- Checker avec le back pour l'initialisation du mode virtuel

2023-09-27 13:14 UTC, Orphidios commented on src/test/xml-request-tester.ts
> +export const getAdrunZoeXmlRequestTest = ({ idam, version, name }: any): string => {
Pas besoin de le rendre paramétrable

2023-10-02 12:14 UTC, dufrenb commented on src/insi-client.service.ts
> +    });
```suggestion
    return Promise.resolve(fetchRequests);
```

ça fonctionne comme ça non ? 🤔

2023-10-03 15:23 UTC, Orphidios approved these changes

2023-10-03 15:25 UTC, merged